//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingManagement_FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Barn()
        {
            this.Storing_products = new HashSet<Storing_products>();
        }
    
        public int Barn_no { get; set; }
        public string Barn_name { get; set; }
        public int Land_no { get; set; }
        public double Barn_acreage { get; set; }
        public bool Status { get; set; }
    
        public virtual Land Land { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storing_products> Storing_products { get; set; }
    }
}
