//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingManagement_FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Workspace
    {
        public string Emp_id { get; set; }
        public string Workspace_1 { get; set; }
        public string Workspace_2 { get; set; }
        public string Workspace_location { get; set; }
        public string Workspace_location_2 { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
