//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingManagement_FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_Use
    {
        public string Emp_id { get; set; }
        public int Equi_id { get; set; }
        public Nullable<System.DateTime> Date_receive { get; set; }
        public Nullable<System.DateTime> Date_return { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
