//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingManagement_FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_Storage
    {
        public int Storage_no { get; set; }
        public int Equi_id { get; set; }
        public string Equi_name { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
