//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingManagement_FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        public int Exam_id { get; set; }
        public int Animal_id { get; set; }
        public string Visit_reason { get; set; }
        public string Treatment_given { get; set; }
        public Nullable<System.DateTime> Visit_date { get; set; }
        public int Vet_id { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Vet Vet { get; set; }
    }
}
