//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingManagement_FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field_work_employees2
    {
        public int Work_id { get; set; }
        public string Emp_id { get; set; }
        public string deneme { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Field_works Field_works { get; set; }
    }
}
