//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingManagement_FMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmingManagementSystemEntities : DbContext
    {
        public FarmingManagementSystemEntities()
            : base("name=FarmingManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<Barn> Barns { get; set; }
        public virtual DbSet<Barn_product> Barn_product { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Equipment_Storage> Equipment_Storage { get; set; }
        public virtual DbSet<Equipment_Use> Equipment_Use { get; set; }
        public virtual DbSet<Examination> Examinations { get; set; }
        public virtual DbSet<Farm> Farms { get; set; }
        public virtual DbSet<Farm_Work> Farm_Work { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<Field_works> Field_works { get; set; }
        public virtual DbSet<Land> Lands { get; set; }
        public virtual DbSet<Notice> Notices { get; set; }
        public virtual DbSet<Seed> Seeds { get; set; }
        public virtual DbSet<Seed_Treatment> Seed_Treatment { get; set; }
        public virtual DbSet<Storage_location> Storage_location { get; set; }
        public virtual DbSet<Storing_products> Storing_products { get; set; }
        public virtual DbSet<Vet> Vets { get; set; }
        public virtual DbSet<Employee_Workspace> Employee_Workspace { get; set; }
    }
}
