//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingManagement_FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresetQuery
    {
        public int query_id { get; set; }
        public string query_name { get; set; }
        public string query_description { get; set; }
        public string SQL_statement { get; set; }
        public bool Status { get; set; }
    }
}
