//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingManagement_FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seed()
        {
            this.Field_work_seeds3 = new HashSet<Field_work_seeds3>();
        }
    
        public string Seed_genus { get; set; }
        public string Seed_date { get; set; }
        public Nullable<double> Cultivation_time { get; set; }
    
        public virtual Seed_Treatment Seed_Treatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Field_work_seeds3> Field_work_seeds3 { get; set; }
    }
}
