//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingManagement_FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seed_Treatment
    {
        public string Seed_genus { get; set; }
        public string Pesticide { get; set; }
        public string Control_range { get; set; }
    
        public virtual Seed Seed { get; set; }
    }
}
