//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingManagement_FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storing_products
    {
        public int Barn_no { get; set; }
        public string Emp_id { get; set; }
        public string Stored_product { get; set; }
        public int Stored_quantity { get; set; }
        public System.DateTime Stored_date { get; set; }
        public Nullable<int> Field_no { get; set; }
        public Nullable<int> Farm_no { get; set; }
    
        public virtual Barn Barn { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Farm Farm { get; set; }
        public virtual Field Field { get; set; }
    }
}
