//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingManagement_FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage_location
    {
        public int Storage_no { get; set; }
        public string Storage_location1 { get; set; }
        public double Storage_acreage { get; set; }
        public string Location_name { get; set; }
        public int Land_no { get; set; }
    
        public virtual Land Land { get; set; }
    }
}
